### ISSUE TITLE
[BUG] Had to edit onfleet/request.py to get the OnFleet Python API Wrapper to work on AWS Lambda

### ISSUE THREAD

**Issue by daveherrington** [onfleet/pyonfleet#18]
I'm using the AWS Lambda Python 3.8 runtime, and my pip3 is Python3.8 (I'm using Mac OSX for my local work).  I built the deployment package using:

pip3 install --target ./package pyonfleet

This installed:

backoff-1.10.0
certifi-2020.12.5
chardet-4.0.0
idna-2.10
pyonfleet-1.1.2
ratelimit-2.2.1
requests-2.25.1
urllib3-1.26.3

I zipped these libs with my own code, per AWS Lambda's instructions, and deployed the package to Lambda.

I got this error when trying to run my Lambda:

[ERROR] DistributionNotFound: The 'pyonfleet' distribution was not found and is required by the application
Traceback (most recent call last):
  File "/var/lang/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/var/lang/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/tp-api-onfleet.py", line 54, in <module>
    on = Onfleet(api_key=ONFLEET_API_TOKEN)
  File "/var/task/onfleet/onfleet.py", line 22, in __init__
    self._initialize_resources(self._session)
  File "/var/task/onfleet/onfleet.py", line 33, in _initialize_resources
    setattr(self, endpoint, Endpoint(http_methods, session))
  File "/var/task/onfleet/endpoint.py", line 9, in __init__
    self._generate_request(httpMethod, methodDict)
  File "/var/task/onfleet/endpoint.py", line 18, in _generate_request
    setattr(self, methodName, Request(http_method, uri, self.Session))
  File "/var/task/onfleet/request.py", line 16, in __init__
    "User-Agent": "pyonfleet-" + pkg_resources.require("pyonfleet")[0].version
  File "/var/lang/lib/python3.8/site-packages/pkg_resources/__init__.py", line 899, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/var/lang/lib/python3.8/site-packages/pkg_resources/__init__.py", line 785, in resolve
    raise DistributionNotFound(req, requirers)

Some online research pointed to the fact that AWS Lambda doesn't have a package manager installed.

I happened upon this line in onfleet/requests.py, which uses the package manager to dynamically provide the version number:

            "User-Agent": "pyonfleet-" + pkg_resources.require("pyonfleet")[0].version

I changed this line to use a hard-coded version number, like this, and this fixed my issue, and everything worked as expected:

            "User-Agent": "pyonfleet-1.1.2"

I'm unblocked, but wanted to share this workaround with you, for the benefit of other AWS Lambda users.  Maybe there is another way to determine this version number, without requiring the package manager to be installed?

-Dave

**Comment by jamesliupenn** [comment]
@daveherrington thanks for the feedback, I'll look into a workaround unless someone already knows one for AWS Lambdas :)

**Comment by daveherrington** [comment]
I see that some other libs set the __version__ variable in either the __init__.py file or a __version__.py file invoked by __init__.py.  This would allow the code to read the version from a file, without the need for a package manager.

There is good discussion on this topic here:  https://stackoverflow.com/questions/2058802/how-can-i-get-the-version-defined-in-setup-py-setuptools-in-my-package

-Dave

**Comment by jamesliupenn** [comment]
We're visiting this issue in the coming week, will keep you posted. Thank you for your patience 👍

**Comment by jcpmmx** [comment]
Hi @daveherrington, thanks a lot for the feedback!
I'm taking this one now.
Stay tuned!

**Comment by jcpmmx** [comment]
Sorry for the delay but this has been solved!
