### ISSUE TITLE
[BUG] installation error

### ISSUE THREAD

**Issue by dsong-medmen** [onfleet/pyonfleet#6]
Hello, I'm getting this error when running `pip install pyonfleet`: 

```
onfleet ❯ pip install pyonfleet                                                                                                 ⏎
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pyonfleet
  Downloading https://files.pythonhosted.org/packages/31/1c/e8169cf6e2dc3b7a9d8bfb6480a27548d867c2297559da3c58b52bf13d82/pyonfleet-1.0.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zb/36g7jk8d2t723_w5gv7f1kkjxccswy/T/pip-install-yBdMzx/pyonfleet/setup.py'"'"'; __file__='"'"'/private/var/folders/zb/36g7jk8d2t723_w5gv7f1kkjxccswy/T/pip-install-yBdMzx/pyonfleet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/zb/36g7jk8d2t723_w5gv7f1kkjxccswy/T/pip-install-yBdMzx/pyonfleet/pip-egg-info
         cwd: /private/var/folders/zb/36g7jk8d2t723_w5gv7f1kkjxccswy/T/pip-install-yBdMzx/pyonfleet/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zb/36g7jk8d2t723_w5gv7f1kkjxccswy/T/pip-install-yBdMzx/pyonfleet/setup.py", line 2, in <module>
        import pathlib
    ImportError: No module named pathlib
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by dsong-medmen** [comment]
As a followup, if I install `pathlib` separately and re-run the `pyonfleet` installation, this is the error that comes up: 

```
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zb/36g7jk8d2t723_w5gv7f1kkjxccswy/T/pip-install-fwUUkG/pyonfleet/setup.py'"'"'; __file__='"'"'/private/var/folders/zb/36g7jk8d2t723_w5gv7f1kkjxccswy/T/pip-install-fwUUkG/pyonfleet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/zb/36g7jk8d2t723_w5gv7f1kkjxccswy/T/pip-install-fwUUkG/pyonfleet/pip-egg-info
         cwd: /private/var/folders/zb/36g7jk8d2t723_w5gv7f1kkjxccswy/T/pip-install-fwUUkG/pyonfleet/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zb/36g7jk8d2t723_w5gv7f1kkjxccswy/T/pip-install-fwUUkG/pyonfleet/setup.py", line 5, in <module>
        README = (HERE / "README.md").read_text()
    AttributeError: 'PosixPath' object has no attribute 'read_text'
```

**Comment by jamesliupenn** [comment]
Hi @dsong-medmen, what is your Python version?

**Comment by jamesliupenn** [comment]
Hi @dsong-medmen  according to your logs it looks as if you're trying to install `pyonfleet` using Python 2.7. Please consider upgrading to Python 3, as the library is written in Python 3.7: https://pypi.org/project/pyonfleet/

Please let us know if you were able to get through this installation issue.

**Comment by jamesliupenn** [comment]
Hi @dsong-medmen, any updates on the installation issue? I'll go ahead and close your ticket as we've not heard back from you for a while. If you're still experiencing similar issues, feel free to reach back out!
